name: Publish to S3 Bucket

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy
        uses: leiteszeke/front-app-to-s3@develop
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AWS_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FOLDER: build/
          BUCKET: s3-deployer