name: Publish to S3 Bucket

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Build React App
        uses: leiteszeke/github-react-build@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: yarn install && yarn build
      - name: Publish to S3 Bucket
        uses: actions/aws/cli@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 sync build/ s3://s3-deployer --acl public-read