name: Publish to S3 Bucket

on: push

jobs:
  deploy:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set SSH Key
      uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  build:
    name: Build
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Build and deplot
        uses: leiteszeke/github-react-to-s3@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: yarn install && yarn build
      - name: Publish
        uses: actions/aws/cli@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 sync build/ s3://s3-deployer --acl public-read